// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://liioauwltjcicrjupoke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpaW9hdXdsdGpjaWNyanVwb2tlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzODgzMTYsImV4cCI6MjA2MDk2NDMxNn0.0OQNhbaM9TztSJJhlFJ7Fdfw3t1BJ82nFc3JJcLCzN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);